export const moviments = [
  {
    type: 'credit',
    value: 113,
    date: new Date(),
    name: 'Restaurante do zé',
    category: 'ALIMENTACAO',
  },
  {
    type: 'debit',
    value: 113,
    date: new Date(),
    name: 'Restaurante do zé',
    category: 'SAUDE',
  },
  {
    type: 'credit',
    value: 113,
    date: new Date(),
    name: 'Restaurante do zé',
    category: 'TRANSPORTE',
  },
  {
    type: 'debit',
    value: 113,
    date: new Date(),
    name: 'Restaurante do zé',
    category: 'CASA',
  },
  {
    type: 'debit',
    value: 113,
    date: new Date(),
    name: 'Restaurante do zé',
    category: 'EDUCACAO',
  },
  {
    type: 'credit',
    value: 113,
    date: new Date(),
    name: 'Restaurante do zé',
    category: 'OUTROS',
  },
  {
    type: 'credit',
    value: 113,
    date: new Date(),
    name: 'Restaurante do zé',
    category: 'OUTROS',
  },
  {
    type: 'credit',
    value: 113,
    date: new Date(),
    name: 'Restaurante do zé',
    category: 'OUTROS',
  },
  {
    type: 'credit',
    value: 113,
    date: new Date(),
    name: 'Restaurante do zé',
    category: 'OUTROS',
  },
  {
    type: 'credit',
    value: 113,
    date: new Date(),
    name: 'Restaurante do zé',
    category: 'OUTROS',
  },
  {
    type: 'credit',
    value: 113,
    date: new Date(),
    name: 'Restaurante do zé',
    category: 'OUTROS',
  },
];
